SELECT TOP 1000
	"ID",
	"CLIENT_EMAIL",
	"PLACE_ID_ID",
	"NR_PERSONS",
	"NR_NIGHTS",
	"DATE_TIME",
	"TOTAL_PRICE",
	"STATUS"
FROM "IDEALGUIDE_HDI_IDEALGUIDE_DB_DEPLOYER_1"."APP_DATAMODEL_RESERVATION_HOUSING"